---
- name: Install httpd(apache)
  hosts: apache
  become: true
  roles:
    - apache

- name: Setup apche_vhost
  hosts: apache_vhost
  become: true
  roles:
    - apache_vhost

- name: Install vsftpd on ftpservers when ftpserver group
  hosts: all
  become: true
  roles:
    - ftpserver

- name: Ensure users
  hosts: loop_users
  become: true
  roles:
    - loop_users
